POST http://localhost:5000/api/url/shorten
Content-Type: application/json

{
    "longUrl": "https://media.gettyimages.com/photos/wazir-khan-mosque-lahore-punjab-pakistan-picture-id637623678?s=612x612"
}